# Generated by Django 5.1.2 on 2024-11-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('card_number', models.CharField(max_length=16)),
                ('card_holder', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('is_default', models.BooleanField()),
            ],
        ),
    ]
