# Generated by Django 5.1.1 on 2024-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('card_id', models.CharField(max_length=255, unique=True)),
                ('card_number', models.CharField(max_length=16)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('expiry_date', models.CharField(max_length=3)),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
    ]
