# Generated by Django 5.1.1 on 2024-10-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpaymentmethod',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='cardpaymentmethod',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
    ]
