# Generated by Django 5.1.1 on 2024-10-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cardpaymentmethod_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardpaymentmethod',
            old_name='user',
            new_name='user_id',
        ),
    ]
