# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCards = channel.unary_unary(
                '/payment_service.PaymentService/GetCards',
                request_serializer=payment__pb2.GetCardsRequest.SerializeToString,
                response_deserializer=payment__pb2.GetCardsResponse.FromString,
                _registered_method=True)
        self.CreateCard = channel.unary_unary(
                '/payment_service.PaymentService/CreateCard',
                request_serializer=payment__pb2.CreateCardRequest.SerializeToString,
                response_deserializer=payment__pb2.CreateCardResponse.FromString,
                _registered_method=True)
        self.UpdateCard = channel.unary_unary(
                '/payment_service.PaymentService/UpdateCard',
                request_serializer=payment__pb2.UpdateCardRequest.SerializeToString,
                response_deserializer=payment__pb2.UpdateCardResponse.FromString,
                _registered_method=True)
        self.DeleteCard = channel.unary_unary(
                '/payment_service.PaymentService/DeleteCard',
                request_serializer=payment__pb2.DeleteCardRequest.SerializeToString,
                response_deserializer=payment__pb2.DeleteCardResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCard(self, request, context):
        """fixed typo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCards': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCards,
                    request_deserializer=payment__pb2.GetCardsRequest.FromString,
                    response_serializer=payment__pb2.GetCardsResponse.SerializeToString,
            ),
            'CreateCard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCard,
                    request_deserializer=payment__pb2.CreateCardRequest.FromString,
                    response_serializer=payment__pb2.CreateCardResponse.SerializeToString,
            ),
            'UpdateCard': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCard,
                    request_deserializer=payment__pb2.UpdateCardRequest.FromString,
                    response_serializer=payment__pb2.UpdateCardResponse.SerializeToString,
            ),
            'DeleteCard': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCard,
                    request_deserializer=payment__pb2.DeleteCardRequest.FromString,
                    response_serializer=payment__pb2.DeleteCardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment_service.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment_service.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_service.PaymentService/GetCards',
            payment__pb2.GetCardsRequest.SerializeToString,
            payment__pb2.GetCardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_service.PaymentService/CreateCard',
            payment__pb2.CreateCardRequest.SerializeToString,
            payment__pb2.CreateCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_service.PaymentService/UpdateCard',
            payment__pb2.UpdateCardRequest.SerializeToString,
            payment__pb2.UpdateCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_service.PaymentService/DeleteCard',
            payment__pb2.DeleteCardRequest.SerializeToString,
            payment__pb2.DeleteCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
